name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf libtool pkg-config build-essential \
              libevent-dev libboost-dev libboost-system-dev libboost-filesystem-dev \
              libboost-chrono-dev libboost-test-dev libboost-thread-dev libminiupnpc-dev \
              libzmq3-dev python3

      - name: Build & test
        run: |
          ./autogen.sh
          ./configure --with-incompatible-bdb
          make -j$(nproc)
          make check

